import "../globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const user = await getServerSession(authOptions);
  // console.log("server call", user?.user);

  return (
    <section className="w-screen h-screen flx bg-reen-400 overflow-hidden">
      <Navbar />
      <div className=" h-full flex-1 no-scrollbar   overflow-auto px-2">
        {children}
      </div>
    </section>
  );
}
